# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_KEY }}
        
    - name: building docker image
      uses: docker/build-push-action@v2
      with:
        tags: gcr.io/zs-products/gofr-web:${{ github.sha }}
        context: ./
        file: ./Dockerfile
        push: true

  stage_deployment:
    runs-on: ubuntu-latest
    name: 🚀 Deploy to Stage
    needs: build

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop'}}
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: zs-products
          service_account_key: ${{ secrets.DEPLOY_KEY }}
          export_default_credentials: true

      - name: Update Kubectl component
        run: gcloud --quiet components update kubectl

      - name: Set GCloud Project and Fetch Cluster Credentials
        run: gcloud container clusters get-credentials products-cluster --zone=us-central1 --project=zs-products

      - name: Set Deployment Image
        run: kubectl set image deployment/gofr-web gofr-web=gcr.io/zs-products/gofr-web:${{ github.sha }} --namespace gofr-stage
      
   
        